/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * json-placeholder API
 * json-placeholder API
 * OpenAPI spec version: 1.0.0
 */
import type { Geo } from "./geo";

export interface Address {
  city?: string;
  geo?: Geo;
  street?: string;
  suite?: string;
  zipcode?: string;
}
