/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * json-placeholder API
 * json-placeholder API
 * OpenAPI spec version: 1.0.0
 */

export * from "./address";
export * from "./album";
export * from "./company";
export * from "./geo";
export * from "./photo";
export * from "./user";
