/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * json-placeholder API
 * json-placeholder API
 * OpenAPI spec version: 1.0.0
 */

export interface Photo {
  albumId?: number;
  id?: number;
  thumbnailUrl?: string;
  title?: string;
  url?: string;
}
