/**
 * Generated by orval v6.19.0 🍺
 * Do not edit manually.
 * json-placeholder API
 * json-placeholder API
 * OpenAPI spec version: 1.0.0
 */
import type { Address } from "./address";
import type { Company } from "./company";

export interface User {
  address?: Address;
  company?: Company;
  email?: string;
  id?: number;
  name?: string;
  phone?: string;
  username?: string;
  website?: string;
}
